### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by evkaw** [chrislennon/currency-touchbar#1]
Traceback (most recent call last):
  File "<string>", line 26, in <module>
KeyError: 'rates'

Anyway I could fix this?

**Comment by libroraptor** [comment]
Same error here. Do users need their own access keys for the API?

```
Traceback (most recent call last):
  File "<string>", line 26, in <module>
KeyError: 'rates'
```

**Comment by libroraptor** [comment]
I got it working with https://www.exchangerate-api.com/ but you need to sign up for an access key. The free key that I got today gives 1500 accesses per month.

5000 free accesses per month at https://freecurrencyapi.com/ 

I haven't yet found an API the doesn't need an access key. @chrislennon would it make sense to use the Google Finance API so that the accesses can be tied to the app rather than to individual users?

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import ssl,json,sys
try: # Python 2/3 compatibility
    from urllib.parse import urlparse, urlencode
    from urllib.request import urlopen, Request
    from urllib.error import HTTPError
except ImportError:
    from urlparse import urlparse
    from urllib import urlencode
    from urllib2 import urlopen, Request, HTTPError

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

try:
    url = "https://v6.exchangerate-api.com/v6/**accesskey**/pair/EUR/USD"
    data = urlopen(url, context=ctx)
    obj=json.load(data)
    rate = '%.2f' % obj["conversion_rate"]
    print('€1 = US$' + rate )

except HTTPError as e:
    print('Unable to get data from API')
```
